//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pcb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot initiate backup file, when the program crashes, data may be lost..
        /// </summary>
        public static string cannotInitBackup {
            get {
                return ResourceManager.GetString("cannotInitBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is a command longer than 30000 characters.
        /// </summary>
        public static string commandTooLong {
            get {
                return ResourceManager.GetString("commandTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong data prefix: format must be &quot;data:x command&quot;, space should be inserted.
        /// </summary>
        public static string dataFormatError {
            get {
                return ResourceManager.GetString("dataFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong data value: cannot larger than 7.
        /// </summary>
        public static string dataLargerThan7 {
            get {
                return ResourceManager.GetString("dataLargerThan7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong data value: not a number/byte.
        /// </summary>
        public static string dataNotNum {
            get {
                return ResourceManager.GetString("dataNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty argument.
        /// </summary>
        public static string emptyArgument {
            get {
                return ResourceManager.GetString("emptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorret format.
        /// </summary>
        public static string formatError {
            get {
                return ResourceManager.GetString("formatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occur when reading the file.
        /// </summary>
        public static string ioError {
            get {
                return ResourceManager.GetString("ioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new command&apos;s coordinates error: not a valid integer.
        /// </summary>
        public static string newCoorError {
            get {
                return ResourceManager.GetString("newCoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new command syntax error.
        /// </summary>
        public static string newFormatError {
            get {
                return ResourceManager.GetString("newFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing brackets.
        /// </summary>
        public static string noBracket {
            get {
                return ResourceManager.GetString("noBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right click.
        /// </summary>
        public static string signText {
            get {
                return ResourceManager.GetString("signText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stats command syntax error.
        /// </summary>
        public static string statsFormatError {
            get {
                return ResourceManager.GetString("statsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown dot parameter.
        /// </summary>
        public static string unknownDotPara {
            get {
                return ResourceManager.GetString("unknownDotPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error.
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown function name.
        /// </summary>
        public static string unknownFunctionName {
            get {
                return ResourceManager.GetString("unknownFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown reference.
        /// </summary>
        public static string unknownReference {
            get {
                return ResourceManager.GetString("unknownReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong theme name.
        /// </summary>
        public static string wrongTheme {
            get {
                return ResourceManager.GetString("wrongTheme", resourceCulture);
            }
        }
    }
}
