//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIresources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIresources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pcb.Properties.UIresources", typeof(UIresources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocomplete source setting.
        /// </summary>
        public static string autocompleteSourceSetting {
            get {
                return ResourceManager.GetString("autocompleteSourceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base(top and bottom) block data value.
        /// </summary>
        public static string baseData {
            get {
                return ResourceManager.GetString("baseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base(top and bottom) block id.
        /// </summary>
        public static string baseID {
            get {
                return ResourceManager.GetString("baseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block mode.
        /// </summary>
        public static string blockMode {
            get {
                return ResourceManager.GetString("blockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command to setblock sign.
        /// </summary>
        public static string colorJson {
            get {
                return ResourceManager.GetString("colorJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use clickEvent and setblock to insert § char into the game.
        /// </summary>
        public static string colorJsonUsage {
            get {
                return ResourceManager.GetString("colorJsonUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment selected lines.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy all.
        /// </summary>
        public static string copyAll {
            get {
                return ResourceManager.GetString("copyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB direction.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display space.
        /// </summary>
        public static string displaySpace {
            get {
                return ResourceManager.GetString("displaySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view doc.
        /// </summary>
        public static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editor font.
        /// </summary>
        public static string editorFont {
            get {
                return ResourceManager.GetString("editorFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity names.
        /// </summary>
        public static string entityNames {
            get {
                return ResourceManager.GetString("entityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escape selected text.
        /// </summary>
        public static string escapeSelected {
            get {
                return ResourceManager.GetString("escapeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find next.
        /// </summary>
        public static string findNext {
            get {
                return ResourceManager.GetString("findNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find/replace.
        /// </summary>
        public static string findOrReplace {
            get {
                return ResourceManager.GetString("findOrReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse all.
        /// </summary>
        public static string foldAll {
            get {
                return ResourceManager.GetString("foldAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        public static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate ooc from whole document/selected lines.
        /// </summary>
        public static string generateToolTip {
            get {
                return ResourceManager.GetString("generateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert §.
        /// </summary>
        public static string insertFormatter {
            get {
                return ResourceManager.GetString("insertFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert marker type.
        /// </summary>
        public static string insertType {
            get {
                return ResourceManager.GetString("insertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert random uuid.
        /// </summary>
        public static string insertUUID {
            get {
                return ResourceManager.GetString("insertUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last saved:.
        /// </summary>
        public static string lastSaved {
            get {
                return ResourceManager.GetString("lastSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string loadFile {
            get {
                return ResourceManager.GetString("loadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiline mode.
        /// </summary>
        public static string multiLine {
            get {
                return ResourceManager.GetString("multiLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string newFile {
            get {
                return ResourceManager.GetString("newFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match not found.
        /// </summary>
        public static string noMatch {
            get {
                return ResourceManager.GetString("noMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOC is too long, command:({0}/{1}).
        /// </summary>
        public static string ooc2Long {
            get {
                return ResourceManager.GetString("ooc2Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot open pcb.
        /// </summary>
        public static string openPcbError {
            get {
                return ResourceManager.GetString("openPcbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load a file will overwrite the current document.
        /// </summary>
        public static string overwritePrompt {
            get {
                return ResourceManager.GetString("overwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcb-OOC generator.
        /// </summary>
        public static string pcbName {
            get {
                return ResourceManager.GetString("pcbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to save the document before exiting?.
        /// </summary>
        public static string promptSaveNew {
            get {
                return ResourceManager.GetString("promptSaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you use Regex mode, you also need to escape the text for replacement_(:3 」∠ )_.
        /// </summary>
        public static string regexNeedEscape {
            get {
                return ResourceManager.GetString("regexNeedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace.
        /// </summary>
        public static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace all.
        /// </summary>
        public static string replaceAll {
            get {
                return ResourceManager.GetString("replaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        public static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run python.
        /// </summary>
        public static string runPython {
            get {
                return ResourceManager.GetString("runPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string saveAs {
            get {
                return ResourceManager.GetString("saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string saveFile {
            get {
                return ResourceManager.GetString("saveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scb objectives.
        /// </summary>
        public static string scbObj {
            get {
                return ResourceManager.GetString("scbObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scb tags.
        /// </summary>
        public static string scbTag {
            get {
                return ResourceManager.GetString("scbTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team names.
        /// </summary>
        public static string scbTeam {
            get {
                return ResourceManager.GetString("scbTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocomplete setting.
        /// </summary>
        public static string settingAc {
            get {
                return ResourceManager.GetString("settingAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window/editor settings.
        /// </summary>
        public static string settingGenerator {
            get {
                return ResourceManager.GetString("settingGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to side block data value.
        /// </summary>
        public static string sideData {
            get {
                return ResourceManager.GetString("sideData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to side block id.
        /// </summary>
        public static string sideID {
            get {
                return ResourceManager.GetString("sideID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0},  column {1}.
        /// </summary>
        public static string statsDisplay {
            get {
                return ResourceManager.GetString("statsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected {0} characters.
        /// </summary>
        public static string statsDisplaySelect {
            get {
                return ResourceManager.GetString("statsDisplaySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert to cb setblock.
        /// </summary>
        public static string toCBSetblock {
            get {
                return ResourceManager.GetString("toCBSetblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncomment selected lines.
        /// </summary>
        public static string uncomment {
            get {
                return ResourceManager.GetString("uncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unescape selected text.
        /// </summary>
        public static string unescapeSelected {
            get {
                return ResourceManager.GetString("unescapeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsaved changes detected, do you want to save the document before exiting?.
        /// </summary>
        public static string unsaveDetected {
            get {
                return ResourceManager.GetString("unsaveDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Commands.
        /// </summary>
        public static string updateCommands {
            get {
                return ResourceManager.GetString("updateCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate ooc that will replace only the selected commands(be careful).
        /// </summary>
        public static string updateCommandsTooltip {
            get {
                return ResourceManager.GetString("updateCommandsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use AEC as marker.
        /// </summary>
        public static string useAEC {
            get {
                return ResourceManager.GetString("useAEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use autocomplete.
        /// </summary>
        public static string useAutocomplete {
            get {
                return ResourceManager.GetString("useAutocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use Regex.
        /// </summary>
        public static string useRegex {
            get {
                return ResourceManager.GetString("useRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check update.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB count for each line.
        /// </summary>
        public static string wrapCount {
            get {
                return ResourceManager.GetString("wrapCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-axis length.
        /// </summary>
        public static string xlength {
            get {
                return ResourceManager.GetString("xlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z-axis length.
        /// </summary>
        public static string zlength {
            get {
                return ResourceManager.GetString("zlength", resourceCulture);
            }
        }
    }
}
